---
- name: Remove conflicting packages
  package: pkg={{item}} state=absent
  with_items:
  - httpd

- name: Install IUS repo
  yum: name=https://centos7.iuscommunity.org/ius-release.rpm state=present
  when: ansible_distribution == "CentOS"

- name: Install nginx
  package: pkg=nginx state=present

- name: Install PHP
  package: pkg={{item}} state=present
  with_items:
  - "{{ php_packages.ansible_distribution }}"

- name: Create server root
  file: path=/srv/www owner=nginx group=nginx mode=755 state=directory

- name: Create vhost roots
  file: path=/srv/www/{{ item }} owner=nginx group=nginx mode=750 state=directory
  when: nginx_vhosts is defined
  with_items:
    - "{{ nginx_vhosts }}"

- name: Install nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=0 group=0 mode=644
  notify:
    - restart nginx

- name: Install vhost configs
  template: src=vhosts/{{ item }}.j2 dest=/etc/nginx/conf.d/{{ item }}.conf owner=0 group=0 mode=644
  when: nginx_vhosts is defined
  with_items:
    - "{{ nginx_vhosts }}"
  notify:
    - restart nginx

- name: Install php.ini
  template: src=php.ini.j2 dest=/etc/php.ini owner=0 group=0 mode=644
  notify:
    - restart php-fpm

- name: Install php-fpm config
  template: src=php-fpm.www.conf.j2 dest=/etc/php-fpm.d/www.conf owner=0 group=0 mode=644
  notify:
    - restart php-fpm

- name: Generate custom dhparams
  command: openssl dhparam -out /etc/ssl/dhparams.pem 2048 creates=/etc/ssl/dhparams.pem
  notify:
    - restart nginx

- name: Ensure nginx enabled and running
  service: name=nginx state=started enabled=yes

- name: Ensure php-fpm enabled and running
  service: name=php-fpm state=started enabled=yes

- name: Allow http in firewall
  firewalld: service=http permanent=true state=enabled immediate=yes

- name: Allow https in firewall
  firewalld: service=https permanent=true state=enabled immediate=yes
