---
- name: Install squid
  yum: pkg={{item}} state=present
  with_items:
  - squid

- name: Install squid config
  copy: src=squid.conf dest=/etc/squid/squid.conf owner=0 group=squid mode=0640
  notify:
    - restart squid

- name: Allow squid in firewall
  firewalld: port=80/tcp permanent=true state=enabled
  notify:
    - restart firewalld

- name: Ensure squid running and enabled
  service: name=squid state=started enabled=yes
