---
- name: Install smartmontools
  yum: name=smartmontools state=present

- name: Install smartd.conf configuration
  template: src=smartd.conf.j2 dest=/etc/smartmontools/smartd.conf owner=0 group=0 mode=644
  notify:
    - restart smartd

- name: Ensure smartd enabled and running
  service: name=smartd state=started enabled=yes
