---
- name: Install smartmontools
  yum: name=smartmontools state=present

- name: Install smartd.conf configuration
  template: src=smartd.conf.j2 dest=/etc/smartmontools/smartd.conf owner=0 group=0 mode=644
  notify:
    - restart smartd

- name: Ensure smartd enabled and running
  service: name=smartd state=started enabled=yes

- name: Install CE7 timekeeping
  yum: name=chrony state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Ensure CE7 timekeeper running
  service: name=chronyd state=started enabled=yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
