---
- name: Install Deaths Folly Repository
  yum: name=http://yum.deathsfolly.net/deathsfolly-release-1.0-1.x86_64.rpm state=present

- name: Install EPEL repository
  yum: pkg=epel-release state=present

#install all pkgs that all in-use versions of centos use
- name: Install our base packages
  yum: pkg={{item}} state=present
  with_items:
  - iptraf-ng
  - chrony
  - screen
  - nano
  - wget
  - mtr
  - rsync
  - lsof
  - unzip
  - yum-cron
  - bind-utils
  - mailx
  - ansible

- name: Start and enable needed services
  service: name={{item}} state=started enabled=yes
  with_items:
  - crond
  - chronyd
  - firewalld
  - NetworkManager
  - tuned
  - yum-cron

- name: Stop and disable unneeded services
  service: name={{item}} state=stopped enabled=no
  with_items:
  - iprdump
  - iprinit
  - iprupdate
  - kdump
  - avahi-daemon

- name: Install CentOS 7 yum-cron.conf
  copy: src=ce7-yum-cron.conf dest=/etc/yum/yum-cron.conf owner=0 group=0 mode=644
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Create .scripts directory
  file: path=/root/.scripts owner=0 group=0 mode=700 state=directory

- include: backup.yml

- name: Install reboot notifier
  template: src=rebootnotify.sh.j2 dest=/root/.scripts/rebootnotify.sh owner=0 group=0 mode=700

- name: Setup reboot notifier cron
  cron: name="rebootnotify" special_time=reboot job="sh /root/.scripts/rebootnotify.sh > /dev/null"

- name: Ensure EST set
  file: src=/usr/share/zoneinfo/America/New_York dest=/etc/localtime state=link owner=0 group=0

- name: Disable SELinux
  selinux: state=disabled
