---
- hosts: jupiter.valhalla
  vars_prompt:
    - name: "vm_name"
      prompt: "VM Name?"
      private: no
  tasks:
    - name: Stop VM
      virt: name={{ vm_name }} state=destroyed
    - name: Remove VM zvol
      zfs: name=storage/kvm/{{ vm_name }} state=absent
    - name: Undefine VM
      virt: name={{ vm_name }}
            command=undefine
