---
- name: Push common role
  hosts: all
  roles:
    - common

- name: Push baremetal role
  hosts: baremetal
  roles:
    - baremetal

- name: Push centos role
  hosts: centos
  roles:
    - centos

- name: Push nginx role
  hosts: nginx
  roles:
    - nginx

- name: Push mariadb role
  hosts: mariadb
  roles:
    - mariadb

- name: Push freebsd role
  hosts: freebsd
  roles:
    - freebsd

- name: Push pxe role
  hosts: pxe
  roles:
    - pxe

- name: Push yumcache role
  hosts: yumcache
  roles:
    - yumcache

- name: Push cpanel role
  hosts: cpanel
  roles:
    - cpanel
