---
- name: Push base role
  hosts: all
  strategy: free
  roles:
    - base

- name: Push baremetal role
  hosts: baremetal
  strategy: free 
  roles:
    - baremetal

- name: Push yumcache role
  hosts: yumcache
  strategy: free 
  roles:
    - yumcache

- name: Push cpanel role
  hosts: cpanel
  strategy: free 
  roles:
    - cpanel

