---
- name: Push base role
  hosts: all
  strategy: free
  roles:
    - base

- name: Push baremetal role
  hosts: baremetal
  strategy: free 
  roles:
    - baremetal

- name: Push nginx role
  hosts: nginx
  strategy: free 
  roles:
    - nginx
  vars:
    php_packages:
      FreeBSD:
        - []
      CentOS:
        - ["php56u-fpm","php56u-mysqlnd","php56u-mbstring","gcc","php56u-pear","php56u-devel","php56u-opcache","php56u-gd"]


- name: Push mariadb role
  hosts: mariadb
  strategy: free 
  roles:
    - mariadb

- name: Push yumcache role
  hosts: yumcache
  strategy: free 
  roles:
    - yumcache

- name: Push cpanel role
  hosts: cpanel
  strategy: free 
  roles:
    - cpanel

- name: push icinga role
  hosts: icinga
  strategy: free 
  roles:
    - icinga
