---
- name: Push base role
  hosts: all
  roles:
    - base

- name: Push baremetal role
  hosts: baremetal
  roles:
    - baremetal

- name: Push nginx role
  hosts: nginx
  roles:
    - nginx

- name: Push mariadb role
  hosts: mariadb
  roles:
    - mariadb

- name: Push pxe role
  hosts: pxe
  roles:
    - pxe

- name: Push yumcache role
  hosts: yumcache
  roles:
    - yumcache

- name: Push cpanel role
  hosts: cpanel
  roles:
    - cpanel
