---
- name: Push common role
  hosts: all
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
  roles:
    - common

- name: Push baremetal role
  hosts: baremetal
  roles:
    - baremetal

- name: Push centos role
  hosts: centos
  roles:
    - centos
