- name: Install our base packages
  yum: pkg={{item}} state=present
  with_items:
  - screen
  - pidgin
  - htop
  - guake
  - thunderbird
  - keepassx
  - gedit
  - git
  - lynx
  - sshpass
  - owncloud-client
  - NetworkManager-openvpn-gnome

- name: Remove unneeded packages
  yum: pkg={{item}} state=absent
  with_items:
  - xfdashboard
  - geany
  - pragha
  - xfburn
  - abiword
  - gnumeric
  - yumex


- name: Disable public SSH port
  firewalld: service=ssh permanent=true state=disabled immediate=yes

