- name: Install our base packages
  yum: pkg={{item}} state=present
  with_items:
  - screen
  - pidgin
  - htop
  - guake
  - thunderbird
  - keepassx
  - gedit
  - git
  - lynx

- name: Stop and disable unneeded services
  service: name={{item}} state=stopped enabled=no
  with_items:
  - sshd

- name: Disable SELinux
  selinux: state=disabled

- name: Remove unneeded packages
  yum: pkg={{item}} state=absent
  with_items:
  - xfdashboard
  - geany
  - pragha
  - xfburn
  - abiword
  - gnumeric

