- name: Install OwnCloud repo
  get_url: url=http://download.opensuse.org/repositories/isv:ownCloud:desktop/Fedora_{{ ansible_distribution_major_version }}/isv:ownCloud:desktop.repo dest=/etc/yum.repos.d/owncloud.repo mode=644

- name: Install our base packages
  yum: pkg={{item}} state=present
  with_items:
  - screen
  - pidgin
  - htop
  - guake
  - thunderbird
  - keepassx
  - gedit
  - git
  - lynx
  - sshpass
  - owncloud-client

- name: Remove unneeded packages
  yum: pkg={{item}} state=absent
  with_items:
  - xfdashboard
  - geany
  - pragha
  - xfburn
  - abiword
  - gnumeric
  - yumex


- name: Disable public SSH port
  firewalld: service=ssh permanent=true state=disabled immediate=yes

