- name: Install our base packages
  yum: pkg={{item}} state=present
  with_items:
  - screen
  - pidgin
  - htop
  - guake
  - thunderbird
  - keepassx
  - gedit
  - git
  - lynx
  - sshpass
  - owncloud-client
  - NetworkManager-openvpn-gnome
  - "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"

- name: Remove unneeded packages
  yum: pkg={{item}} state=absent
  with_items:
  - xfdashboard
  - geany
  - pragha
  - xfburn
  - abiword
  - gnumeric
  - yumex
  - claws-mail
  - midori
  - leafpad

- name: Disable public SSH port
  firewalld: service=ssh permanent=true state=disabled immediate=yes

