---
- name: Install mariadb
  yum: pkg=mariadb-server state=present

- name: Install mariadb settings file
  copy: src=mysettings.cnf dest=/etc/my.cnf.d/mysettings.cnf owner=0 group=0 mode=644

- name: Ensure mariadb enabled and running
  service: name=mariadb state=started enabled=yes
