---
- name: Install mariadb and dependencies
  yum: pkg={{ item }} state=present
  with_items:
    - mariadb-server
    - MySQL-python

- name: Install mariadb settings file
  copy: src=mysettings.cnf dest=/etc/my.cnf.d/mysettings.cnf owner=0 group=0 mode=644

- name: Ensure mariadb enabled and running
  service: name=mariadb state=started enabled=yes

- include: rotatepass.yml

- name: Ensure safe perms on .my.cnf
  file: path=/root/.my.cnf owner=0 group=0 mode=600

- name: Remove anonymous user
  mysql_user: name="" state="absent"

- name: Remove test database
  mysql_db: name=test state=absent

