- name: Generate random root password
  command: /usr/bin/openssl rand -base64 16
  register: root_passwd
  changed_when: False

- name: Remove unneeded root user
  mysql_user: name=root host={{ ansible_fqdn }} state=absent

- name: Set root password
  mysql_user: name=root host={{ item }} password={{ root_passwd.stdout }}
  changed_when: False
  with_items:
    - "127.0.0.1"
    - "::1"
    - "localhost" #must be last
  when: ansible_check_mode == False

- name: Set root user
  ini_file: dest=/root/.my.cnf
            section=client
            option=user
            value=root

- name: Save root password
  ini_file: dest=/root/.my.cnf
            section=client
            option=password
            value={{ root_passwd.stdout }}
  changed_when: False
  when: ansible_check_mode == False
