---
- name: Install needed packages
  pkgng: name={{ item }} state=present
  with_items:
    - nano
    - mtr-nox11
    - arping
    - pftop
    - bind-tools
    - rsync
    - screen
    - sshguard-pf

- name: Set EST
  file: src=/usr/share/zoneinfo/America/New_York dest=/etc/localtime state=link owner=0 group=0 force=yes

- name: Install PF config
  template: src=pf.conf.j2 dest=/etc/pf.conf owner=0 group=0 mode=600
  notify:
    - reload pf

- name: Enable PF
  lineinfile: dest=/etc/rc.conf regexp=^pf_enable line=pf_enable=\"YES\"

- name: Install tty config
  copy: src=ttys dest=/etc/ttys owner=0 group=0 mode=644
  notify:
    - reload init

- name: Disable TCP listen for syslogd
  lineinfile: dest=/etc/rc.conf regexp=^syslogd_flags line=syslogd_flags=\"-ss\"
  notify:
    - restart syslogd

- name: Install profile template
  template: src=dot.profile dest=/usr/share/skel/dot.profile owner=0 group=0 mode=644

#dangit digital ocean :(
- name: Remove freebsd user
  user: name=freebsd state=absent remove=yes

- name: Remove DigitalOcean configs
  file: path={{ item }} state=absent
  with_items:
    - /etc/rc.d/digitalocean

- name: Configure sysctl
  copy: src=sysctl.conf dest=/etc/sysctl.conf owner=0 group=0 mode=644
  notify:
    - apply sysctl

- name: Install jail config
  template: src=jail.conf.j2 dest=/etc/jail.conf owner=0 group=0 mode=600

- name: Enable sshguard
  lineinfile: dest=/etc/rc.conf regexp=^sshguard_enable line=sshguard_enable=\"YES\"
  notify:
    - restart sshguard

