---
- name: Install needed packages
  pkgng: name={{ item }} state=present
  with_items:
    - nano
    - mtr-nox11

- name: Install PF config
  template: src=pf.conf.j2 dest=/etc/pf.conf owner=0 group=0 mode=600
  notify:
    - reload pf

- name: Enable PF
  lineinfile: dest=/etc/rc.conf regexp=^pf_enable line=pf_enable=\"YES\"

- name: Disable TCP listen for syslogd
  lineinfile: dest=/etc/rc.conf regexp=^syslogd_flags line=syslogd_flags=\"-ss\"
  notify:
    - restart syslogd

